//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntoTheCode.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntoTheCode.Message.MessageRes", typeof(MessageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting identifier, found EOF..
        /// </summary>
        public static string itc01 {
            get {
                return ResourceManager.GetString("itc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting string, found EOF..
        /// </summary>
        public static string itc03 {
            get {
                return ResourceManager.GetString("itc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting string ending..
        /// </summary>
        public static string itc05 {
            get {
                return ResourceManager.GetString("itc05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting symbol &apos;{1}&apos;, found &apos;{2}&apos;.
        /// </summary>
        public static string itc07 {
            get {
                return ResourceManager.GetString("itc07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting value for expression..
        /// </summary>
        public static string itc08 {
            get {
                return ResourceManager.GetString("itc08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting {1}, found {2}..
        /// </summary>
        public static string itc10 {
            get {
                return ResourceManager.GetString("itc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}, colomn {1}.
        /// </summary>
        public static string LineAndCol {
            get {
                return ResourceManager.GetString("LineAndCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First rule &apos;{0} must represent all document and have Tag=true.
        /// </summary>
        public static string p01 {
            get {
                return ResourceManager.GetString("p01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read &apos;{0}&apos;.
        /// </summary>
        public static string p02 {
            get {
                return ResourceManager.GetString("p02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntoTheCode developer error: {0}.
        /// </summary>
        public static string p03 {
            get {
                return ResourceManager.GetString("p03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grammar rules.
        /// </summary>
        public static string p04 {
            get {
                return ResourceManager.GetString("p04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of input not reached..
        /// </summary>
        public static string p05 {
            get {
                return ResourceManager.GetString("p05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is null..
        /// </summary>
        public static string p06 {
            get {
                return ResourceManager.GetString("p06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: An expression element can&apos;t be siebling with other elements.
        /// </summary>
        public static string pb02 {
            get {
                return ResourceManager.GetString("pb02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The &apos;or&apos; symbol is misplaced in expression.
        /// </summary>
        public static string pb03 {
            get {
                return ResourceManager.GetString("pb03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser factory: No read element for &apos;{0}&apos;.
        /// </summary>
        public static string pb04 {
            get {
                return ResourceManager.GetString("pb04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link grammar {1}. Identifier {0} is defined twice.
        /// </summary>
        public static string pb05 {
            get {
                return ResourceManager.GetString("pb05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; not found in Grammar.
        /// </summary>
        public static string pb06 {
            get {
                return ResourceManager.GetString("pb06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: Identifier &apos;{0}&apos; cant be resolved.
        /// </summary>
        public static string pb07 {
            get {
                return ResourceManager.GetString("pb07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: Identifier &apos;{0}&apos; Property &apos;{1}&apos; cant be resolved.
        /// </summary>
        public static string pb08 {
            get {
                return ResourceManager.GetString("pb08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First rule &apos;{0}&apos; must have Collapse=false.
        /// </summary>
        public static string pb09 {
            get {
                return ResourceManager.GetString("pb09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; must be a positive integer.
        /// </summary>
        public static string pb10 {
            get {
                return ResourceManager.GetString("pb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; must have a non recursive path..
        /// </summary>
        public static string pb11 {
            get {
                return ResourceManager.GetString("pb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). First charactor is not allowed..
        /// </summary>
        public static string pe02 {
            get {
                return ResourceManager.GetString("pe02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting string..
        /// </summary>
        public static string pe04 {
            get {
                return ResourceManager.GetString("pe04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error ({0}). Expecting operator for expression..
        /// </summary>
        public static string pe09 {
            get {
                return ResourceManager.GetString("pe09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse &apos;{0}&apos; to integer (too long)..
        /// </summary>
        public static string pe11 {
            get {
                return ResourceManager.GetString("pe11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something terrible with {0} has happened.
        /// </summary>
        public static string SomeError {
            get {
                return ResourceManager.GetString("SomeError", resourceCulture);
            }
        }
    }
}
