//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntoTheCode.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntoTheCode.Message.MessageRes", typeof(MessageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to run &apos;Custom tool&apos; after editing resources.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Resource is not the right type. Modifiers must be public.
        /// </summary>
        public static string base0001 {
            get {
                return ResourceManager.GetString("base0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open windows event log for writing.
        /// </summary>
        public static string base0002 {
            get {
                return ResourceManager.GetString("base0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource can&apos;t be found: {0}. Add resource file to Post.
        /// </summary>
        public static string base0003 {
            get {
                return ResourceManager.GetString("base0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test message.
        /// </summary>
        public static string base0004 {
            get {
                return ResourceManager.GetString("base0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a UnaryExpression or a MemberExpression.
        /// </summary>
        public static string base0005 {
            get {
                return ResourceManager.GetString("base0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda expression is null.
        /// </summary>
        public static string base0006 {
            get {
                return ResourceManager.GetString("base0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deeper error.
        /// </summary>
        public static string base0007 {
            get {
                return ResourceManager.GetString("base0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devel. only: .
        /// </summary>
        public static string DevelOnly {
            get {
                return ResourceManager.GetString("DevelOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is allready activated.
        /// </summary>
        public static string LicAllreadyActive {
            get {
                return ResourceManager.GetString("LicAllreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component edition &apos;{0} dosn&apos;t match lic file edition &apos;{1}&apos;.
        /// </summary>
        public static string LicEdition {
            get {
                return ResourceManager.GetString("LicEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License fault: .
        /// </summary>
        public static string LicFault {
            get {
                return ResourceManager.GetString("LicFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file read error.
        /// </summary>
        public static string LicFileRead {
            get {
                return ResourceManager.GetString("LicFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License information not found.
        /// </summary>
        public static string LicInfoNotFound {
            get {
                return ResourceManager.GetString("LicInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key (file) is not found.
        /// </summary>
        public static string LicKeyNotFound {
            get {
                return ResourceManager.GetString("LicKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key is not valid.
        /// </summary>
        public static string LicKeyNotValid {
            get {
                return ResourceManager.GetString("LicKeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License signature is not valid.
        /// </summary>
        public static string LicSign {
            get {
                return ResourceManager.GetString("LicSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is too old for this version of component.
        /// </summary>
        public static string LicTooOld {
            get {
                return ResourceManager.GetString("LicTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial period has expired.
        /// </summary>
        public static string LicTrialExpired {
            get {
                return ResourceManager.GetString("LicTrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial edition is for debug mode only.
        /// </summary>
        public static string LicTrialRelease {
            get {
                return ResourceManager.GetString("LicTrialRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown component type.
        /// </summary>
        public static string LicType {
            get {
                return ResourceManager.GetString("LicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License validation error.
        /// </summary>
        public static string LicValidation {
            get {
                return ResourceManager.GetString("LicValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for activation.
        /// </summary>
        public static string LicWaiting {
            get {
                return ResourceManager.GetString("LicWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text channel &apos;{0}&apos; not working.
        /// </summary>
        public static string MsgChannelError {
            get {
                return ResourceManager.GetString("MsgChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception happened.
        /// </summary>
        public static string MsgUnhandledException {
            get {
                return ResourceManager.GetString("MsgUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry read error.
        /// </summary>
        public static string RegistryRead {
            get {
                return ResourceManager.GetString("RegistryRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry read permission error.
        /// </summary>
        public static string RegistryReadPermission {
            get {
                return ResourceManager.GetString("RegistryReadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry write error.
        /// </summary>
        public static string RegistryWrite {
            get {
                return ResourceManager.GetString("RegistryWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry write access error.
        /// </summary>
        public static string RegistryWriteAccess {
            get {
                return ResourceManager.GetString("RegistryWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry write permission error.
        /// </summary>
        public static string RegistryWritePermission {
            get {
                return ResourceManager.GetString("RegistryWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something terrible with {0} has happened.
        /// </summary>
        public static string SomeError {
            get {
                return ResourceManager.GetString("SomeError", resourceCulture);
            }
        }
    }
}
